export const countryToISO3 = (countryName) => {
    if (!countryName) return '';

    const mapping = {
        'Andorra': 'AND',
        'United Arab Emirates': 'ARE',
        'Afghanistan': 'AFG',
        'Antigua and Barbuda': 'ATG',
        'Anguilla': 'AIA',
        'Albania': 'ALB',
        'Armenia': 'ARM',
        'Angola': 'AGO',
        'Antarctica': 'ATA',
        'Argentina': 'ARG',
        'American Samoa': 'ASM',
        'Austria': 'AUT',
        'Australia': 'AUS',
        'Aruba': 'ABW',
        'Åland Islands': 'ALA',
        'Azerbaijan': 'AZE',
        'Bosnia and Herzegovina': 'BIH',
        'Barbados': 'BRB',
        'Bangladesh': 'BGD',
        'Belgium': 'BEL',
        'Burkina Faso': 'BFA',
        'Bulgaria': 'BGR',
        'Bahrain': 'BHR',
        'Burundi': 'BDI',
        'Benin': 'BEN',
        'Saint Barthélemy': 'BLM',
        'Bermuda': 'BMU',
        'Brunei Darussalam': 'BRN',
        'Bolivia': 'BOL',
        'Bonaire, Sint Eustatius and Saba': 'BES',
        'Brazil': 'BRA',
        'Bahamas': 'BHS',
        'Bhutan': 'BTN',
        'Bouvet Island': 'BVT',
        'Botswana': 'BWA',
        'Belarus': 'BLR',
        'Belize': 'BLZ',
        'Canada': 'CAN',
        'Cocos (Keeling) Islands': 'CCK',
        'Congo, Democratic Republic of the': 'COD',
        'Central African Republic': 'CAF',
        'Congo': 'COG',
        'Switzerland': 'CHE',
        'Côte d\'Ivoire': 'CIV',
        'Cook Islands': 'COK',
        'Chile': 'CHL',
        'Cameroon': 'CMR',
        'China': 'CHN',
        'Colombia': 'COL',
        'Costa Rica': 'CRI',
        'Cuba': 'CUB',
        'Cabo Verde': 'CPV',
        'Curaçao': 'CUW',
        'Christmas Island': 'CXR',
        'Cyprus': 'CYP',
        'Czechia': 'CZE',
        'Germany': 'DEU',
        'Djibouti': 'DJI',
        'Denmark': 'DNK',
        'Dominica': 'DMA',
        'Dominican Republic': 'DOM',
        'Algeria': 'DZA',
        'Ecuador': 'ECU',
        'Estonia': 'EST',
        'Egypt': 'EGY',
        'Western Sahara': 'ESH',
        'Eritrea': 'ERI',
        'Spain': 'ESP',
        'Ethiopia': 'ETH',
        'Finland': 'FIN',
        'Fiji': 'FJI',
        'Falkland Islands (Malvinas)': 'FLK',
        'Micronesia (Federated States of)': 'FSM',
        'Faroe Islands': 'FRO',
        'France': 'FRA',
        'Gabon': 'GAB',
        'United Kingdom': 'GBR',
        'UK': 'GBR',
        'Grenada': 'GRD',
        'Georgia': 'GEO',
        'French Guiana': 'GUF',
        'Guernsey': 'GGY',
        'Ghana': 'GHA',
        'Gibraltar': 'GIB',
        'Greenland': 'GRL',
        'Gambia': 'GMB',
        'Guinea': 'GIN',
        'Guadeloupe': 'GLP',
        'Equatorial Guinea': 'GNQ',
        'Greece': 'GRC',
        'South Georgia and the South Sandwich Islands': 'SGS',
        'Guatemala': 'GTM',
        'Guam': 'GUM',
        'Guinea-Bissau': 'GNB',
        'Guyana': 'GUY',
        'Hong Kong': 'HKG',
        'Heard Island and McDonald Islands': 'HMD',
        'Honduras': 'HND',
        'Croatia': 'HRV',
        'Haiti': 'HTI',
        'Hungary': 'HUN',
        'Indonesia': 'IDN',
        'Ireland': 'IRL',
        'Israel': 'ISR',
        'Isle of Man': 'IMN',
        'India': 'IND',
        'British Indian Ocean Territory': 'IOT',
        'Iraq': 'IRQ',
        'Iran (Islamic Republic of)': 'IRN',
        'Iceland': 'ISL',
        'Italy': 'ITA',
        'Jersey': 'JEY',
        'Jamaica': 'JAM',
        'Jordan': 'JOR',
        'Japan': 'JPN',
        'Kenya': 'KEN',
        'Kyrgyzstan': 'KGZ',
        'Cambodia': 'KHM',
        'Kiribati': 'KIR',
        'Comoros': 'COM',
        'Saint Kitts and Nevis': 'KNA',
        'Korea (Democratic People\'s Republic of)': 'PRK',
        'Korea, Republic of': 'KOR',
        'South Korea': 'KOR',
        'North Korea': 'PRK',
        'Kuwait': 'KWT',
        'Cayman Islands': 'CYM',
        'Kazakhstan': 'KAZ',
        'Lao People\'s Democratic Republic': 'LAO',
        'Lebanon': 'LBN',
        'Saint Lucia': 'LCA',
        'Liechtenstein': 'LIE',
        'Sri Lanka': 'LKA',
        'Liberia': 'LBR',
        'Lesotho': 'LSO',
        'Lithuania': 'LTU',
        'Luxembourg': 'LUX',
        'Latvia': 'LVA',
        'Libya': 'LBY',
        'Morocco': 'MAR',
        'Monaco': 'MCO',
        'Moldova, Republic of': 'MDA',
        'Montenegro': 'MNE',
        'Saint Martin (French part)': 'MAF',
        'Madagascar': 'MDG',
        'Marshall Islands': 'MHL',
        'North Macedonia': 'MKD',
        'Mali': 'MLI',
        'Myanmar': 'MMR',
        'Mongolia': 'MNG',
        'Macao': 'MAC',
        'Northern Mariana Islands': 'MNP',
        'Martinique': 'MTQ',
        'Mauritania': 'MRT',
        'Montserrat': 'MSR',
        'Malta': 'MLT',
        'Mauritius': 'MUS',
        'Maldives': 'MDV',
        'Malawi': 'MWI',
        'Mexico': 'MEX',
        'Malaysia': 'MYS',
        'Mozambique': 'MOZ',
        'Namibia': 'NAM',
        'New Caledonia': 'NCL',
        'Niger': 'NER',
        'Norfolk Island': 'NFK',
        'Nigeria': 'NGA',
        'Nicaragua': 'NIC',
        'Netherlands': 'NLD',
        'Norway': 'NOR',
        'Nepal': 'NPL',
        'Nauru': 'NRU',
        'Niue': 'NIU',
        'New Zealand': 'NZL',
        'Oman': 'OMN',
        'Panama': 'PAN',
        'Peru': 'PER',
        'French Polynesia': 'PYF',
        'Papua New Guinea': 'PNG',
        'Philippines': 'PHL',
        'Pakistan': 'PAK',
        'Poland': 'POL',
        'Saint Pierre and Miquelon': 'SPM',
        'Pitcairn': 'PCN',
        'Puerto Rico': 'PRI',
        'Palestine, State of': 'PSE',
        'Portugal': 'PRT',
        'Palau': 'PLW',
        'Paraguay': 'PRY',
        'Qatar': 'QAT',
        'Réunion': 'REU',
        'Romania': 'ROU',
        'Serbia': 'SRB',
        'Russian Federation': 'RUS',
        'Russia': 'RUS',
        'Rwanda': 'RWA',
        'Saudi Arabia': 'SAU',
        'Solomon Islands': 'SLB',
        'Seychelles': 'SYC',
        'Sudan': 'SDN',
        'Sweden': 'SWE',
        'Singapore': 'SGP',
        'Saint Helena, Ascension and Tristan da Cunha': 'SHN',
        'Slovenia': 'SVN',
        'Svalbard and Jan Mayen': 'SJM',
        'Slovakia': 'SVK',
        'Sierra Leone': 'SLE',
        'San Marino': 'SMR',
        'Senegal': 'SEN',
        'Somalia': 'SOM',
        'Suriname': 'SUR',
        'South Sudan': 'SSD',
        'Sao Tome and Principe': 'STP',
        'El Salvador': 'SLV',
        'Sint Maarten (Dutch part)': 'SXM',
        'Syrian Arab Republic': 'SYR',
        'Eswatini': 'SWZ',
        'Turks and Caicos Islands': 'TCA',
        'Chad': 'TCD',
        'French Southern Territories': 'ATF',
        'Togo': 'TGO',
        'Thailand': 'THA',
        'Tajikistan': 'TJK',
        'Tokelau': 'TKL',
        'Timor-Leste': 'TLS',
        'Turkmenistan': 'TKM',
        'Tunisia': 'TUN',
        'Tonga': 'TON',
        'Türkiye': 'TUR',
        'Turkey': 'TUR',
        'Trinidad and Tobago': 'TTO',
        'Tuvalu': 'TUV',
        'Taiwan, Province of China': 'TWN',
        'Tanzania, United Republic of': 'TZA',
        'Ukraine': 'UKR',
        'Uganda': 'UGA',
        'United States Minor Outlying Islands': 'UMI',
        'United States of America': 'USA',
        'USA': 'USA',
        'Uruguay': 'URY',
        'Uzbekistan': 'UZB',
        'Holy See': 'VAT',
        'Saint Vincent and the Grenadines': 'VCT',
        'Venezuela (Bolivarian Republic of)': 'VEN',
        'Virgin Islands (British)': 'VGB',
        'Virgin Islands (U.S.)': 'VIR',
        'Viet Nam': 'VNM',
        'Vanuatu': 'VUT',
        'Wallis and Futuna': 'WLF',
        'Samoa': 'WSM',
        'Yemen': 'YEM',
        'Mayotte': 'MYT',
        'South Africa': 'ZAF',
        'Zambia': 'ZMB',
        'Zimbabwe': 'ZWE'
    };

    return mapping[countryName] || countryName.substring(0, 3).toUpperCase();
};
